# Version of CircleCI object
version: 2.1

# Workflow containing all jobs and requirements
workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
      - deploy:
          filters:
            branches:
              only:
                - main
          requires:
            - build

jobs:
# Build job located in the current project directory and containing steps
  build:
    working_directory: ~/4th-Year-DevOpsSec-Project
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@5'
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-npm
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
  
  # Deployment job and steps with Environment Variables and activation trigger involving the script bash file
  deploy:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - run:
          name: deploy-application
          command: ssh -o StrictHostKeyChecking=no $EC2_USERNAME@$EC2_PUBLIC_DNS "rm -rf 4thYearProject/;git clone https://github.com/Efeighery/GamingSiteProject.git; source 4thYearProject/deploy.sh"
